[package]
name = "spin-router-middleware"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.77"
spin-sdk = "2"
task-local-extensions = "0.1.4"

[dev-dependencies]
tokio-test = "*"
