spin_manifest_version = 2

[application]
name = "cors-tester"
version = "0.1.0"
authors = ["Christian Hoffmann <hffmnn@googlemail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "cors-tester"

[component.cors-tester]
source = "target/wasm32-wasi/release/cors_tester.wasm"
allowed_outbound_hosts = []
[component.cors-tester.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
